services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LLM=${LLM}
      - DB_HOST=database
      - DB_USER=${DB_USER:-team5admin}
      - DB_PASSWORD=${DB_PASSWORD:-mysecretpassword}
      - DB_NAME=${DB_NAME:-harvard_db}
    volumes:
      - .:/app
      - ~/.cache:/root/.cache
    networks:
      - app-network
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: team5admin
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: harvard_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
