

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}  # Reference the API key from the .env file
    volumes:
      - .:/app
      - ~/.cache:/root/.cache
    networks:
      - app-network
    ports:
      - "8000:8000"
    depends_on:
      - database
      - redis

  database:
    image: postgres:13-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    networks:
      - app-network
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
